---

- hosts: debian_physical
  serial: 1
  order: shuffle
  roles:
   - debian_physical
   - lxd_debian

- hosts: freebsd_common
  roles:
   - freebsd_common

- hosts: alpine_common
  roles:
   - alpine_common
