---

- hosts: debian_physical
  serial: 1
  order: shuffle
  roles:
   - debian_physical
   - lxd_debian
   - k3s_debian

- hosts: alpine_common
  roles:
   - alpine_common

- hosts: freebsd_common
  roles:
   - freebsd_common

- hosts: nameservers
  roles:
   - keepalived
   - unbound_alpine

- hosts: minio_nodes
  roles:
   - container_static_ip
   - minio

- hosts: etcd_nodes
  roles:
   - container_static_ip
   - etcd

- hosts: cockroachdb_nodes
  roles:
   - keepalived
   - cockroachdb_tls

- hosts: registry_nodes
  roles:
   - keepalived
   - container_static_ip
   - docker-registry

- hosts: haproxy_nodes
  roles:
   - keepalived
   - haproxy

- hosts: postgres_nodes
  roles:
   - postgres

- hosts: elasticsearch_nodes
  roles:
   - container_static_ip
   - elasticsearch

- hosts: jenkins_nodes
  roles:
   - jenkins
